language: java

before_install:
    - sudo apt-get update
    - sudo apt -y install wget curl
    - sudo add-apt-repository ppa:linuxuprising/java
    - sudo apt update
    - sudo apt install oracle-java14-installer
    - sudo apt install oracle-java14-set-default